type Person = {
  name: string;
  tableNumber: number;
};

const data: Person[] = [
  { name: 'Wes Ackeman', tableNumber: 12 },
  { name: 'Amber Ackerman', tableNumber: 12 },
  { name: 'Brad Andersen', tableNumber: 7 },
  { name: 'Crystal Andersen', tableNumber: 7 },
  { name: 'Devin Andersen', tableNumber: 7 },
  { name: 'Heather Andersen', tableNumber: 7 },
  { name: 'Kylee Andersen', tableNumber: 7 },
  { name: 'Morgan Andersen', tableNumber: 7 },
  { name: 'Tyler Andersen', tableNumber: 7 },
  { name: 'Rachel Billings', tableNumber: 12 },
  { name: 'Colton Bradshaw', tableNumber: 5 },
  { name: 'Jaelyn & Dawson Bradshaw', tableNumber: 5 },
  { name: 'Jon Bradshaw', tableNumber: 5 },
  { name: 'Tanner Bradshaw', tableNumber: 5 },
  { name: 'Daniel Brown', tableNumber: 13 },
  { name: 'Jessica Brown', tableNumber: 13 },
  { name: 'Carolyn Brunson', tableNumber: 2 },
  { name: 'Warren Brunson', tableNumber: 2 },
  { name: 'Jake Butters', tableNumber: 15 },
  { name: 'Kate Butters', tableNumber: 15 },
  { name: 'Maija Carlson', tableNumber: 8 },
  { name: 'Abby Chaffin', tableNumber: 16 },
  { name: 'Garrett Chaffin', tableNumber: 16 },
  { name: 'Rachel Clare', tableNumber: 17 },
  { name: 'Nathan Clark', tableNumber: 13 },
  { name: 'Clarissa England', tableNumber: 14 },
  { name: 'Jeff England', tableNumber: 14 },
  { name: 'Ryan Goff', tableNumber: 15 },
  { name: 'Sage Green', tableNumber: 13 },
  { name: 'Kevin Gunnell', tableNumber: 8 },
  { name: 'Sara Gunnell', tableNumber: 8 },
  { name: 'Hannah Hansen', tableNumber: 13 },
  { name: 'Andrew Harward', tableNumber: 17 },
  { name: 'Haley Harward', tableNumber: 17 },
  { name: 'Julian Harward', tableNumber: 10 },
  { name: 'Lacie Harward', tableNumber: 10 },
  { name: 'Rod Harward', tableNumber: 10 },
  { name: 'Sharon Harward', tableNumber: 10 },
  { name: 'Zack Harward', tableNumber: 16 },
  { name: 'Jahna Hatch', tableNumber: 14 },
  { name: 'Linda Hatch', tableNumber: 5 },
  { name: 'Ryan Hatch', tableNumber: 14 },
  { name: 'Curtis Hixon', tableNumber: 14 },
  { name: 'Micah Hixon', tableNumber: 14 },
  { name: 'Tyler Housley', tableNumber: 2 },
  { name: 'Andrea Kertamus', tableNumber: 11 },
  { name: 'Hyrum Kertamus', tableNumber: 11 },
  { name: 'Layne Kertamus', tableNumber: 11 },
  { name: 'Aaron Kestler', tableNumber: 15 },
  { name: 'Aaron Law', tableNumber: 8 },
  { name: 'Collin Law', tableNumber: 9 },
  { name: 'Craig Law', tableNumber: 8 },
  { name: 'Janet Law', tableNumber: 8 },
  { name: 'Kellie Law', tableNumber: 9 },
  { name: 'Mallory Law', tableNumber: 9 },
  { name: 'Matt Law', tableNumber: 9 },
  { name: 'Norah Law', tableNumber: 9 },
  { name: 'Patrick Law', tableNumber: 9 },
  { name: 'Sarah Law', tableNumber: 9 },
  { name: 'Seth Law', tableNumber: 9 },
  { name: 'Toby Law', tableNumber: 9 },
  { name: 'Savannah McDonald', tableNumber: 17 },
  { name: 'Cass Miller', tableNumber: 15 },
  { name: 'Brady Mitchell', tableNumber: 12 },
  { name: 'Elisa Mitchell', tableNumber: 12 },
  { name: 'Tommy Moncur', tableNumber: 15 },
  { name: 'Christian Morris', tableNumber: 15 },
  { name: 'Kayla Morris', tableNumber: 15 },
  { name: 'Drew Mortenson', tableNumber: 13 },
  { name: 'Taylor Naser', tableNumber: 17 },
  { name: 'Kaylee Oakeson', tableNumber: 2 },
  { name: 'Mike Oakeson', tableNumber: 2 },
  { name: 'Connely Packard', tableNumber: 15 },
  { name: 'Jayson Pemberton', tableNumber: 17 },
  { name: 'Natalie Pemberton', tableNumber: 17 },
  { name: 'Bob Price', tableNumber: 8 },
  { name: 'Dave Price', tableNumber: 8 },
  { name: 'Eva Price', tableNumber: 8 },
  { name: 'Melanie Price', tableNumber: 8 },
  { name: 'Weston Price', tableNumber: 7 },
  { name: 'Albina Rasmussen', tableNumber: 13 },
  { name: 'Zach Rasmussen', tableNumber: 13 },
  { name: 'Becky Richards', tableNumber: 6 },
  { name: 'Brooke Richards', tableNumber: 16 },
  { name: 'Colleen Richards', tableNumber: 6 },
  { name: 'Mark Richards', tableNumber: 6 },
  { name: 'Spencer Richards', tableNumber: 6 },
  { name: 'Emily Rogers', tableNumber: 14 },
  { name: 'Parker Rogers', tableNumber: 14 },
  { name: 'Aaron Roper', tableNumber: 17 },
  { name: 'Avery Roper', tableNumber: 10 },
  { name: 'Brent Roper', tableNumber: 6 },
  { name: 'Brian Roper', tableNumber: 6 },
  { name: 'Cami Roper', tableNumber: 1 },
  { name: 'Chris Roper', tableNumber: 6 },
  { name: 'Darson Roper', tableNumber: 3 },
  { name: 'Duane Roper', tableNumber: 1 },
  { name: 'Geniel Roper', tableNumber: 3 },
  { name: 'Jake Roper', tableNumber: 16 },
  { name: 'Lizzy & Chrissy Roper', tableNumber: 17 },
  { name: 'Meleea Roper', tableNumber: 6 },
  { name: 'Ron Roper', tableNumber: 10 },
  { name: 'Ryan Roper', tableNumber: 3 },
  { name: 'Sham Roper', tableNumber: 16 },
  { name: 'Stacey Roper', tableNumber: 6 },
  { name: 'Steven Roper', tableNumber: 3 },
  { name: 'Taylor & Darby Roper', tableNumber: 3 },
  { name: 'Tori Roper', tableNumber: 10 },
  { name: 'Vail Roper', tableNumber: 10 },
  { name: 'Wade Roper', tableNumber: 10 },
  { name: 'Carissa & Jackson Schwendiman', tableNumber: 5 },
  { name: 'Kristjan Schwendiman', tableNumber: 5 },
  { name: 'Kylie Schwendiman', tableNumber: 5 },
  { name: 'Anne Smith', tableNumber: 12 },
  { name: 'Ben Smith', tableNumber: 12 },
  { name: 'Marissa Stotts', tableNumber: 12 },
  { name: "Breanne Su'a", tableNumber: 16 },
  { name: "Sai Su'a", tableNumber: 16 },
  { name: 'Audrey & Adi Summers', tableNumber: 3 },
  { name: 'Brandon Summers', tableNumber: 3 },
  { name: 'Jackson Summers', tableNumber: 3 },
  { name: 'DJ Swenson', tableNumber: 7 },
  { name: 'Aaron Tibbitt', tableNumber: 4 },
  { name: 'Bre Tibbitt', tableNumber: 4 },
  { name: 'Chris Tibbitt', tableNumber: 4 },
  { name: 'Dan Tibbitt', tableNumber: 4 },
  { name: 'Jeff Tibbitt', tableNumber: 4 },
  { name: 'Justin Tibbitt', tableNumber: 4 },
  { name: 'Karen Tibbitt', tableNumber: 4 },
  { name: 'Matt Tibbitt', tableNumber: 4 },
  { name: 'Megan Tibbitt', tableNumber: 4 },
  { name: 'Jeremy Troff', tableNumber: 14 },
  { name: 'Katie Troff', tableNumber: 14 },
  { name: 'Jon Van Wagenen', tableNumber: 5 },
  { name: 'Susanne Vest', tableNumber: 5 },
  { name: 'Adam Westover', tableNumber: 2 },
  { name: 'Bryce Westover', tableNumber: 1 },
  { name: 'Charlotte Westover', tableNumber: 12 },
  { name: 'Christy Westover', tableNumber: 11 },
  { name: 'Cole Westover', tableNumber: 11 },
  { name: 'Denise Westover', tableNumber: 11 },
  { name: 'Helen & Maya Westover', tableNumber: 2 },
  { name: 'Jeremy Westover', tableNumber: 11 },
  { name: 'Jordan Westover', tableNumber: 1 },
  { name: 'Laura Westover', tableNumber: 1 },
  { name: 'Megan Westover', tableNumber: 1 },
  { name: 'MeShell Westover', tableNumber: 2 },
  { name: 'Neil Westover', tableNumber: 11 },
  { name: 'Spencer Westover', tableNumber: 2 },
  { name: 'Hallie Wilkinson', tableNumber: 3 },
];
export default data;
